Advanced actions hw
evgendiy/AQA25_onl pull request #4
Opened 2024-04-13 00:14 UTC by evgendiy

Added advanced actions homework

2024-04-21 16:11 UTC, wildpioneer requested changes

2024-04-21 16:11 UTC, wildpioneer commented on src/test/java/FileUploadTest.java
> +        String pathToFile = ActionsTest.class.getClassLoader().getResource("image.jpg").getPath().substring(1);
Ошибка компиляции - потому как этого класса в этом бранче нет

2024-04-21 16:11 UTC, wildpioneer commented on src/test/java/DownloadTest.java
> +        waitsService.waitForElementClickable(By.xpath("//a[@href='download/IMG_0239.jpg']")).click();
У меня не оказалось такого файла и тест упал

2024-04-21 16:40 UTC, evgendiy commented on src/test/java/FileUploadTest.java
> +        String pathToFile = ActionsTest.class.getClassLoader().getResource("image.jpg").getPath().substring(1);
Исправил

2024-04-21 16:41 UTC, evgendiy commented on src/test/java/DownloadTest.java
> +        waitsService.waitForElementClickable(By.xpath("//a[@href='download/IMG_0239.jpg']")).click();
На сайте изменился список файлов, перепишу тест

2024-04-29 09:41 UTC, wildpioneer commented
Проверено

2024-04-29 09:41 UTC, closed without merging